export const ADD_TASK = 'ADD_TASK'
export const EDIT_TASk = 'EDIT_TASk'
export const FILTER_TASK = 'FILTER_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const FILTER_TASKS = 'FILTER_TASKS'
export const UPDATE_TASK ='UPDATE_TASK'
